table Fact_orderinvoice
	lineageTag: 0a086918-e1d3-4be3-a192-8d7d1b6406bf

	measure 'List of NS_QuoteLine values' = ```
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[SF_QuoteLine_Id])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[SF_QuoteLine_Id]),
			                    'Fact_orderinvoice'[SF_QuoteLine_Id],
			                    ASC
			                ),
			                
			" • "
			& 'Fact_orderinvoice'[SF_QuoteLine_Id],
			               UNICHAR
			(
			10
			),
			                 
			" • "
			&'Fact_orderinvoice'[SF_QuoteLine_Id],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[SF_QuoteLine_Id]),
			             
			" • "
			&'Fact_orderinvoice'[SF_QuoteLine_Id],
			            UNICHAR
			(
			10
			),
			             
			" • "
			&'Fact_orderinvoice'[SF_QuoteLine_Id],
			            ASC
			        )
			    )
			```
		lineageTag: 54b5a623-5594-4d3d-bf58-35eab29404aa

	measure 'List of SF_NSStatus values' =
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[SF_NSStatus])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[SF_NSStatus]),
			                    'Fact_orderinvoice'[SF_NSStatus],
			                    ASC
			                ),
			                'Fact_orderinvoice'[SF_NSStatus],
			                ", ",
			                'Fact_orderinvoice'[SF_NSStatus],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[SF_NSStatus]),
			            'Fact_orderinvoice'[SF_NSStatus],
			            ", ",
			            'Fact_orderinvoice'[SF_NSStatus],
			            ASC
			        )
			    )
		lineageTag: ace6cbe7-c555-447a-92a2-a548131f23d9

	measure 'List of NS_Invoice_Delivery_Status values' = ```
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[NS_Invoice_Delivery_Status])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[NS_Invoice_Delivery_Status]),
			                    'Fact_orderinvoice'[NS_Invoice_Delivery_Status],
			                    ASC
			                ),
			                 
			" • "
			&'Fact_orderinvoice'[NS_Invoice_Delivery_Status],
			               UNICHAR
			(
			10
			),
			                
			" • "
			& 'Fact_orderinvoice'[NS_Invoice_Delivery_Status],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[NS_Invoice_Delivery_Status]),
			             
			" • "
			&'Fact_orderinvoice'[NS_Invoice_Delivery_Status],
			            UNICHAR
			(
			10
			),
			             
			" • "
			&'Fact_orderinvoice'[NS_Invoice_Delivery_Status],
			            ASC
			        )
			    )
			```
		lineageTag: 9e8679f0-17ec-4b8e-b831-f9b1f3b80e2e

	measure 'List of NS_PaymentStatus values' =
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[NS_PaymentStatus])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[NS_PaymentStatus]),
			                    'Fact_orderinvoice'[NS_PaymentStatus],
			                    ASC
			                ),
			                " • " &'Fact_orderinvoice'[NS_PaymentStatus],
			                UNICHAR(10),
			                " • " &'Fact_orderinvoice'[NS_PaymentStatus],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[NS_PaymentStatus]),
			            " • " &'Fact_orderinvoice'[NS_PaymentStatus],
			            UNICHAR(10),
			            " • " &'Fact_orderinvoice'[NS_PaymentStatus],
			            ASC
			        )
			    )
		lineageTag: d83e056f-a16e-49fc-b7c6-b4ebc432740e

	measure 'List of NS_PO_Needed values' =
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[NS_PO_Needed])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[NS_PO_Needed]),
			                    'Fact_orderinvoice'[NS_PO_Needed],
			                    ASC
			                ),
			                " • " &'Fact_orderinvoice'[NS_PO_Needed],
			                UNICHAR(10),
			                " • " &'Fact_orderinvoice'[NS_PO_Needed],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[NS_PO_Needed]),
			            " • " &'Fact_orderinvoice'[NS_PO_Needed],
			            UNICHAR(10),
			            " • " &'Fact_orderinvoice'[NS_PO_Needed],
			            ASC
			        )
			    )
		lineageTag: 063759ab-43c1-469b-b82c-f9bf4c37630f

	measure 'List of NS_InvoiceNumber values' =
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[NS_InvoiceNumber])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[NS_InvoiceNumber]),
			                    'Fact_orderinvoice'[NS_InvoiceNumber],
			                    ASC
			                ),
			                " • " &'Fact_orderinvoice'[NS_InvoiceNumber],
			                UNICHAR(10),
			                " • " &'Fact_orderinvoice'[NS_InvoiceNumber],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[NS_InvoiceNumber]),
			            " • " &'Fact_orderinvoice'[NS_InvoiceNumber],
			            UNICHAR(10),
			            " • " &'Fact_orderinvoice'[NS_InvoiceNumber],
			            ASC
			        )
			    )
		lineageTag: a9fa6f4c-3711-4239-be2d-68d2d82f429e

	measure 'List of NS_AmountInTransactionalCurrency values' =
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[NS_AmountInTransactionalCurrency])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[NS_AmountInTransactionalCurrency]),
			                    'Fact_orderinvoice'[NS_AmountInTransactionalCurrency],
			                    ASC
			                ),
			                " • " & 'Fact_orderinvoice'[NS_AmountInTransactionalCurrency],
			                UNICHAR(10),
			                " • " & 'Fact_orderinvoice'[NS_AmountInTransactionalCurrency],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[NS_AmountInTransactionalCurrency]),
			            " • " & 'Fact_orderinvoice'[NS_AmountInTransactionalCurrency],
			            UNICHAR(10),
			            " • " & 'Fact_orderinvoice'[NS_AmountInTransactionalCurrency],
			            ASC
			        )
			    )
		lineageTag: 227fcbb0-f175-41fb-b6f4-482cdaefd94d

	measure 'List of NS_AmountInSubCurrency values' =
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[NS_AmountInSubCurrency])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[NS_AmountInSubCurrency]),
			                    'Fact_orderinvoice'[NS_AmountInSubCurrency],
			                    ASC
			                ),
			                " • " & 'Fact_orderinvoice'[NS_AmountInSubCurrency],
			                UNICHAR
			(
			10
			),
			                " • " & 'Fact_orderinvoice'[NS_AmountInSubCurrency],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[NS_AmountInSubCurrency]),
			            " • " & 'Fact_orderinvoice'[NS_AmountInSubCurrency],
			           UNICHAR
			(
			10
			),
			            " • " & 'Fact_orderinvoice'[NS_AmountInSubCurrency],
			            ASC
			        )
			    )
		lineageTag: 7b992a64-c9da-466b-b4ed-3650bf9670a0

	measure 'List of NS_InvoiceBillingFrequencyHeader values' =
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[NS_InvoiceBillingFrequencyHeader])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[NS_InvoiceBillingFrequencyHeader]),
			                    'Fact_orderinvoice'[NS_InvoiceBillingFrequencyHeader],
			                    ASC
			                ),
			                " • " & 'Fact_orderinvoice'[NS_InvoiceBillingFrequencyHeader],
			                 UNICHAR(10),
			                " • " & 'Fact_orderinvoice'[NS_InvoiceBillingFrequencyHeader],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[NS_InvoiceBillingFrequencyHeader]),
			            " • " & 'Fact_orderinvoice'[NS_InvoiceBillingFrequencyHeader],
			             UNICHAR(10),
			            " • " & 'Fact_orderinvoice'[NS_InvoiceBillingFrequencyHeader],
			            ASC
			        )
			    )
		lineageTag: d99a6d6a-60d1-404e-abee-4f1f3a7c3427

	measure 'List of NS_InvoiceBillingFrequencyLine values' =
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[NS_InvoiceBillingFrequencyLine])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[NS_InvoiceBillingFrequencyLine]),
			                    'Fact_orderinvoice'[NS_InvoiceBillingFrequencyLine],
			                    ASC
			                ),
			                " • " &'Fact_orderinvoice'[NS_InvoiceBillingFrequencyLine],
			                 UNICHAR(10),
			                " • " &'Fact_orderinvoice'[NS_InvoiceBillingFrequencyLine],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[NS_InvoiceBillingFrequencyLine]),
			            " • " &'Fact_orderinvoice'[NS_InvoiceBillingFrequencyLine],
			             UNICHAR(10),
			            " • " &'Fact_orderinvoice'[NS_InvoiceBillingFrequencyLine],
			            ASC
			        )
			    )
		lineageTag: 75b8a623-a198-4a4f-8d2d-f138addde474

	measure 'List of NS_Revenue_Type values' =
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[NS_Revenue_Type])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[NS_Revenue_Type]),
			                    'Fact_orderinvoice'[NS_Revenue_Type],
			                    ASC
			                ),
			                " • " &'Fact_orderinvoice'[NS_Revenue_Type],
			                UNICHAR(10),
			                " • " &'Fact_orderinvoice'[NS_Revenue_Type],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[NS_Revenue_Type]),
			            " • " &'Fact_orderinvoice'[NS_Revenue_Type],
			            UNICHAR(10),
			            " • " &'Fact_orderinvoice'[NS_Revenue_Type],
			            ASC
			        )
			    )
		lineageTag: f695f544-613e-4a8b-b35c-26da3e4470d2

	measure 'List of NS_SubsidiaryCurrency values' =
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[NS_SubsidiaryCurrency])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[NS_SubsidiaryCurrency]),
			                    'Fact_orderinvoice'[NS_SubsidiaryCurrency],
			                    ASC
			                ),
			                " • " &'Fact_orderinvoice'[NS_SubsidiaryCurrency],
			                UNICHAR(10),
			                " • " &'Fact_orderinvoice'[NS_SubsidiaryCurrency],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[NS_SubsidiaryCurrency]),
			            " • " &'Fact_orderinvoice'[NS_SubsidiaryCurrency],
			            UNICHAR(10),
			            " • " &'Fact_orderinvoice'[NS_SubsidiaryCurrency],
			            ASC
			        )
			    )
		lineageTag: df0f9070-dbf2-4763-9d53-657ab6e18ef0

	measure 'List of NS_BillingScheduleStartDate values' =
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[NS_BillingScheduleStartDate])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[NS_BillingScheduleStartDate]),
			                    'Fact_orderinvoice'[NS_BillingScheduleStartDate],
			                    ASC
			                ),
			                " • " &'Fact_orderinvoice'[NS_BillingScheduleStartDate],
			               UNICHAR(10),
			                " • " &'Fact_orderinvoice'[NS_BillingScheduleStartDate],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[NS_BillingScheduleStartDate]),
			            " • " &'Fact_orderinvoice'[NS_BillingScheduleStartDate],
			            UNICHAR(10),
			            " • " &'Fact_orderinvoice'[NS_BillingScheduleStartDate],
			            ASC
			        )
			    )
		lineageTag: 37fcd50b-156b-4548-ba01-781db6cdd104

	measure 'List of NS_BillingScheduleEndDate values' =
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[NS_BillingScheduleEndDate])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[NS_BillingScheduleEndDate]),
			                    'Fact_orderinvoice'[NS_BillingScheduleEndDate],
			                    ASC
			                ),
			                " • " &'Fact_orderinvoice'[NS_BillingScheduleEndDate],
			                UNICHAR(10),
			                " • " &'Fact_orderinvoice'[NS_BillingScheduleEndDate],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[NS_BillingScheduleEndDate]),
			            " • " &'Fact_orderinvoice'[NS_BillingScheduleEndDate],
			            UNICHAR(10),
			            " • " &'Fact_orderinvoice'[NS_BillingScheduleEndDate],
			            ASC
			        )
			    )
		lineageTag: a8f4d5b0-33e3-41bf-8bfa-b861a7bfbf93

	measure 'List of SF_Order_Item_Id values' = ```
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[SF_Order_Item_Id])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[SF_Order_Item_Id]),
			                    'Fact_orderinvoice'[SF_Order_Item_Id],
			                    ASC
			                ),
			                 
			" • "
			&'Fact_orderinvoice'[SF_Order_Item_Id],
			                UNICHAR
			(
			10
			),
			                 
			" • "
			&'Fact_orderinvoice'[SF_Order_Item_Id],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[SF_Order_Item_Id]),
			             
			" • "
			&'Fact_orderinvoice'[SF_Order_Item_Id],
			            UNICHAR
			(
			10
			),
			            
			" • "
			& 'Fact_orderinvoice'[SF_Order_Item_Id],
			            ASC
			        )
			    )
			```
		lineageTag: fa01ab42-5029-4666-85e8-e87232ccab8b

	measure 'List of SF_Opportunity_Product_Id values' = ```
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[SF_Opportunity_Product_Id])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[SF_Opportunity_Product_Id]),
			                    'Fact_orderinvoice'[SF_Opportunity_Product_Id],
			                    ASC
			                ),
			                 
			" • "
			&'Fact_orderinvoice'[SF_Opportunity_Product_Id],
			                UNICHAR
			(
			10
			),
			                 
			" • "
			&'Fact_orderinvoice'[SF_Opportunity_Product_Id],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[SF_Opportunity_Product_Id]),
			             
			" • "
			&'Fact_orderinvoice'[SF_Opportunity_Product_Id],
			            UNICHAR
			(
			10
			),
			             
			" • "
			&'Fact_orderinvoice'[SF_Opportunity_Product_Id],
			            ASC
			        )
			    )
			```
		lineageTag: 96fe3343-3901-439d-b82c-243b7741ff7a

	measure 'List of NS_RevenueStartDate values' =
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[NS_RevenueStartDate])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[NS_RevenueStartDate]),
			                    'Fact_orderinvoice'[NS_RevenueStartDate],
			                    ASC
			                ),
			                " • " &'Fact_orderinvoice'[NS_RevenueStartDate],
			                UNICHAR(10),
			                " • " &'Fact_orderinvoice'[NS_RevenueStartDate],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[NS_RevenueStartDate]),
			            " • " &'Fact_orderinvoice'[NS_RevenueStartDate],
			            UNICHAR(10),
			            " • " &'Fact_orderinvoice'[NS_RevenueStartDate],
			            ASC
			        )
			    )
		lineageTag: 2431199c-0c1b-4329-8744-6b498dca1adb

	measure 'List of NS_RevenueEndDate values' =
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[NS_RevenueEndDate])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[NS_RevenueEndDate]),
			                    'Fact_orderinvoice'[NS_RevenueEndDate],
			                    ASC
			                ),
			                " • " &'Fact_orderinvoice'[NS_RevenueEndDate],
			                UNICHAR(10),
			                " • " &'Fact_orderinvoice'[NS_RevenueEndDate],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[NS_RevenueEndDate]),
			            " • " &'Fact_orderinvoice'[NS_RevenueEndDate],
			            UNICHAR(10),
			            " • " &'Fact_orderinvoice'[NS_RevenueEndDate],
			            ASC
			        )
			    )
		lineageTag: 96784dd1-8dda-4de8-bd73-d08ea819111a

	measure 'List of NS_SO_InternalID values' =
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[NS_SO_InternalID])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[NS_SO_InternalID]),
			                    'Fact_orderinvoice'[NS_SO_InternalID],
			                    ASC
			                ),
			                " • " &'Fact_orderinvoice'[NS_SO_InternalID],
			                UNICHAR(10),
			                " • " &'Fact_orderinvoice'[NS_SO_InternalID],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[NS_SO_InternalID]),
			            " • " &'Fact_orderinvoice'[NS_SO_InternalID],
			            UNICHAR(10),
			            " • " &'Fact_orderinvoice'[NS_SO_InternalID],
			            ASC
			        )
			    )
		lineageTag: acc1d396-ab56-4ad3-98e7-8ccefac58093

	measure 'List of NS_MonthlyAvgExchangeRate values' =
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[NS_MonthlyAvgExchangeRate])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[NS_MonthlyAvgExchangeRate]),
			                    'Fact_orderinvoice'[NS_MonthlyAvgExchangeRate],
			                    ASC
			                ),
			                " • " &'Fact_orderinvoice'[NS_MonthlyAvgExchangeRate],
			                UNICHAR(10),
			                " • " &'Fact_orderinvoice'[NS_MonthlyAvgExchangeRate],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[NS_MonthlyAvgExchangeRate]),
			            " • " &'Fact_orderinvoice'[NS_MonthlyAvgExchangeRate],
			            UNICHAR(10),
			            " • " &'Fact_orderinvoice'[NS_MonthlyAvgExchangeRate],
			            ASC
			        )
			    )
		lineageTag: e4b9584d-1976-4edc-b392-779014d80e6d

	measure 'List of NS_Period values' =
			
			VAR __DISTINCT_VALUES_COUNT = DISTINCTCOUNT('Fact_orderinvoice'[NS_Period])
			VAR __MAX_VALUES_TO_SHOW = 20
			RETURN
			    IF(
			        __DISTINCT_VALUES_COUNT > __MAX_VALUES_TO_SHOW,
			        CONCATENATE(
			            CONCATENATEX(
			                TOPN(
			                    __MAX_VALUES_TO_SHOW,
			                    VALUES('Fact_orderinvoice'[NS_Period]),
			                    'Fact_orderinvoice'[NS_Period],
			                    ASC
			                ),
			                " • " &'Fact_orderinvoice'[NS_Period],
			                UNICHAR(10),
			                " • " &'Fact_orderinvoice'[NS_Period],
			                ASC
			            ),
			            ", etc."
			        ),
			        CONCATENATEX(
			            VALUES('Fact_orderinvoice'[NS_Period]),
			            " • " &'Fact_orderinvoice'[NS_Period],
			            UNICHAR(10),
			            " • " &'Fact_orderinvoice'[NS_Period],
			            ASC
			        )
			    )
		lineageTag: 7b4ef417-db93-4892-b7af-c66715313df1

	column SF_Quote_Id
		dataType: string
		lineageTag: a4244c15-169a-41d1-9837-7a56f1ceba8a
		summarizeBy: none
		sourceColumn: SF_Quote_Id

		annotation SummarizationSetBy = Automatic

	column SF_QuoteLine_Id
		dataType: string
		lineageTag: d4c445b4-f758-4013-8cf1-0c9ce8c7026d
		summarizeBy: none
		sourceColumn: SF_QuoteLine_Id

		annotation SummarizationSetBy = Automatic

	column SF_Opportunity_Product_Id
		dataType: string
		lineageTag: d7c9b9e9-7f80-499b-b802-734887588476
		summarizeBy: none
		sourceColumn: SF_Opportunity_Product_Id

		annotation SummarizationSetBy = Automatic

	column SF_Order_Item_Id
		dataType: string
		lineageTag: d1de63ed-7460-44a1-a1a2-2e2e1686cb83
		summarizeBy: none
		sourceColumn: SF_Order_Item_Id

		annotation SummarizationSetBy = Automatic

	column SF_SBQQ__HasConsumptionSchedule__c
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 756fe031-34e1-435d-a8a2-da02f2799576
		summarizeBy: none
		sourceColumn: SF_SBQQ__HasConsumptionSchedule__c

		annotation SummarizationSetBy = Automatic

	column SF_SBQQ__SubscriptionStartDate__c
		dataType: int64
		formatString: 0
		lineageTag: 26acd2d8-e1f3-4cfb-af8a-d3fd68a8010f
		summarizeBy: sum
		sourceColumn: SF_SBQQ__SubscriptionStartDate__c

		annotation SummarizationSetBy = Automatic

	column SF_SBQQ__SubscriptionEndDate__c
		dataType: string
		lineageTag: 5ba76c8e-04ac-4709-b78b-789ea2e2ef17
		summarizeBy: none
		sourceColumn: SF_SBQQ__SubscriptionEndDate__c

		annotation SummarizationSetBy = Automatic

	column SF_ContractStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: d9f70ad1-0933-4230-a643-dbb2f23c1869
		summarizeBy: none
		sourceColumn: SF_ContractStartDate

		variation Variation
			isDefault
			relationship: 1639e976-0084-4bc1-93a7-acab72d0e749
			defaultHierarchy: LocalDateTable_c0448318-9f1d-42f3-8c86-38c994663afe.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SF_ContractEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: df4c1624-b6c6-485a-949b-67a4f0169a60
		summarizeBy: none
		sourceColumn: SF_ContractEndDate

		variation Variation
			isDefault
			relationship: 555e1334-90a3-424c-a7b7-e52244442265
			defaultHierarchy: LocalDateTable_87967730-50cd-48b6-b0e1-383e614c8d51.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column SF_SalesOrder_Id__c
		dataType: string
		lineageTag: 6a044f2f-499f-4fc9-aec8-827f22676a99
		summarizeBy: none
		sourceColumn: SF_SalesOrder_Id__c

		annotation SummarizationSetBy = Automatic

	column CL_Net_Price_Total
		dataType: double
		lineageTag: 69f86683-2492-4383-90d2-cbc758de51ea
		summarizeBy: sum
		sourceColumn: CL_Net_Price_Total

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CL_Conversion_Rate
		dataType: double
		lineageTag: 81dd3955-7018-4d4b-a117-8e455dd1bca7
		summarizeBy: sum
		sourceColumn: CL_Conversion_Rate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CL_Net_Price_USD
		dataType: double
		lineageTag: 8f303860-27ac-4950-b0e5-d89e7d207a21
		summarizeBy: sum
		sourceColumn: CL_Net_Price_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CL_Total_Forecasted_Loss_USD
		dataType: double
		lineageTag: f4218087-e6d6-4616-99b8-160cdccfe9b2
		summarizeBy: sum
		sourceColumn: CL_Total_Forecasted_Loss_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column SF_NSStatus
		dataType: string
		lineageTag: ed264bb1-5ee4-44e1-88f6-6d4c2fe95365
		summarizeBy: none
		sourceColumn: SF_NSStatus

		annotation SummarizationSetBy = Automatic

	column NS_Invoice_Delivery_Status
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 76b61dcb-0baf-4d25-8e86-c5085152d2c5
		summarizeBy: none
		sourceColumn: NS_Invoice_Delivery_Status

		annotation SummarizationSetBy = Automatic

	column NS_PaymentStatus
		dataType: string
		lineageTag: 2309a13d-10fb-41b0-b7bc-f5d670637ddb
		summarizeBy: none
		sourceColumn: NS_PaymentStatus

		annotation SummarizationSetBy = Automatic

	column NS_PO_Needed
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: bf480c05-b715-4b41-a6e8-a5faf1bbb4c4
		summarizeBy: none
		sourceColumn: NS_PO_Needed

		annotation SummarizationSetBy = Automatic

	column NS_InvoiceNumber
		dataType: string
		lineageTag: 55559efd-b7de-41fe-88c2-b7a8cb0ec2c3
		summarizeBy: none
		sourceColumn: NS_InvoiceNumber

		annotation SummarizationSetBy = Automatic

	column NS_AmountInTransactionalCurrency
		dataType: string
		lineageTag: ef7663c0-b565-4346-82f1-274cab89abb7
		summarizeBy: none
		sourceColumn: NS_AmountInTransactionalCurrency

		annotation SummarizationSetBy = Automatic

	column NS_AmountInSubCurrency
		dataType: string
		lineageTag: 551411ee-e80c-4c00-aacc-f0738259b20c
		summarizeBy: none
		sourceColumn: NS_AmountInSubCurrency

		annotation SummarizationSetBy = Automatic

	column NS_InvoiceBillingFrequencyHeader
		dataType: string
		lineageTag: dc0e9945-35b2-4991-8cba-c216ca040c21
		summarizeBy: none
		sourceColumn: NS_InvoiceBillingFrequencyHeader

		annotation SummarizationSetBy = Automatic

	column NS_InvoiceBillingFrequencyLine
		dataType: string
		lineageTag: b6e056ef-67c3-4d48-8f53-2fa31ee8b4d2
		summarizeBy: none
		sourceColumn: NS_InvoiceBillingFrequencyLine

		annotation SummarizationSetBy = Automatic

	column NS_Revenue_Type
		dataType: string
		lineageTag: f4644637-f644-4443-bf6e-b067516ba327
		summarizeBy: none
		sourceColumn: NS_Revenue_Type

		annotation SummarizationSetBy = Automatic

	column NS_SubsidiaryCurrency
		dataType: string
		lineageTag: 7964b941-82c1-4fb2-adb0-b5aca9bf3239
		summarizeBy: none
		sourceColumn: NS_SubsidiaryCurrency

		annotation SummarizationSetBy = Automatic

	column NS_BillingScheduleStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: cc0c05f8-4942-4ba7-a872-3390c0daa31f
		summarizeBy: none
		sourceColumn: NS_BillingScheduleStartDate

		variation Variation
			isDefault
			relationship: 479a948c-c874-4ed7-8d11-46cab70bb7a2
			defaultHierarchy: LocalDateTable_9848b5d4-5a35-455c-9e00-71b42e6f4a22.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column NS_BillingScheduleEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 8aa63a78-fbf1-4e9f-8595-c53602608b48
		summarizeBy: none
		sourceColumn: NS_BillingScheduleEndDate

		variation Variation
			isDefault
			relationship: f8dac8cf-6db2-4b15-9145-1a94e8325064
			defaultHierarchy: LocalDateTable_f9106fe3-1c6e-4e44-a4f3-f7d1a7900128.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column NS_RevenueStartDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7a5de136-d156-470e-af56-075c121c052f
		summarizeBy: none
		sourceColumn: NS_RevenueStartDate

		variation Variation
			isDefault
			relationship: 6953ffca-6c0c-43d6-a6e3-f3c0dc466350
			defaultHierarchy: LocalDateTable_9121bd9b-8ace-4dde-a9e4-56902d251d1d.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column NS_RevenueEndDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: 56a28b3d-464b-4ed2-8544-e86f003eeb18
		summarizeBy: none
		sourceColumn: NS_RevenueEndDate

		variation Variation
			isDefault
			relationship: 7c58fbac-fcd3-4159-98c7-c18c684d0f69
			defaultHierarchy: LocalDateTable_b0876ec7-c315-450e-80d2-620c8843aa4f.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column NS_SO_InternalID
		dataType: string
		lineageTag: 83ce983e-f48e-4a94-b41e-6088cdf2a33d
		summarizeBy: none
		sourceColumn: NS_SO_InternalID

		annotation SummarizationSetBy = Automatic

	column NS_MonthlyAvgExchangeRate
		dataType: double
		lineageTag: 0b77f87c-c687-4690-b24b-8f4023556b73
		summarizeBy: sum
		sourceColumn: NS_MonthlyAvgExchangeRate

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column CL_AmountUSD
		dataType: double
		lineageTag: b6d593ac-a723-4c2f-a761-73f47f602b25
		summarizeBy: sum
		sourceColumn: CL_AmountUSD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column NS_Period
		dataType: string
		lineageTag: 09769062-bbb8-4ff2-a917-2e9a5ca7b4b2
		summarizeBy: none
		sourceColumn: NS_Period

		annotation SummarizationSetBy = Automatic

	partition Fact_orderinvoice = m
		mode: import
		source =
				let
				    Source = Sql.Database("sqldb-analytics-prod.database.windows.net", "dwh-sql-prod", [Query="select SF_Quote_Id,#(lf)SF_QuoteLine_Id,#(lf)SF_Opportunity_Product_Id,#(lf)SF_Order_Item_Id,#(lf)SF_SBQQ__HasConsumptionSchedule__c,#(lf)SF_SBQQ__SubscriptionStartDate__c,#(lf)SF_SBQQ__SubscriptionEndDate__c,#(lf)SF_ContractStartDate,#(lf)SF_ContractEndDate,#(lf)SF_SalesOrder_Id__c,#(lf)CL_Net_Price_Total,#(lf)CL_Conversion_Rate,#(lf)CL_Net_Price_USD,#(lf)CL_Total_Forecasted_Loss_USD,#(lf)SF_NSStatus,#(lf)NS_Invoice_Delivery_Status,#(lf)NS_PaymentStatus,#(lf)NS_PO_Needed,#(lf)NS_InvoiceNumber,#(lf)NS_AmountInTransactionalCurrency,#(lf)NS_AmountInSubCurrency,#(lf)NS_InvoiceBillingFrequencyHeader,#(lf)NS_InvoiceBillingFrequencyLine,#(lf)NS_Revenue_Type,#(lf)NS_SubsidiaryCurrency,#(lf)NS_BillingScheduleStartDate,#(lf)NS_BillingScheduleEndDate,#(lf)NS_RevenueStartDate,#(lf)NS_RevenueEndDate,#(lf)NS_SO_InternalID,#(lf)NS_MonthlyAvgExchangeRate,#(lf)CL_AmountUSD,#(lf)NS_Period from DWH.Fact_orderinvoice", CreateNavigationProperties=false]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"NS_BillingScheduleStartDate", type date}, {"NS_BillingScheduleEndDate", type date}, {"NS_RevenueStartDate", type date}, {"NS_RevenueEndDate", type date}, {"SF_ContractStartDate", type date}, {"SF_ContractEndDate", type date}, {"SF_SBQQ__SubscriptionEndDate__c", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

